- name: Apache HTTPD
  hosts: default
  become: yes
  tasks:
    - name: Install Apache HTTPD
      yum:
        name:
          - httpd
          - mod_ssl
        state: present

    - name: Enable Apache HTTPD
      systemd:
        name: httpd
        enabled: yes
